
package stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CurrencyrateService", targetNamespace = "http://currencyrate/", wsdlLocation = "http://localhost:8080/currencyserver/CurrencyrateService?WSDL")
public class CurrencyrateService
    extends Service
{

    private final static URL CURRENCYRATESERVICE_WSDL_LOCATION;
    private final static WebServiceException CURRENCYRATESERVICE_EXCEPTION;
    private final static QName CURRENCYRATESERVICE_QNAME = new QName("http://currencyrate/", "CurrencyrateService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/currencyserver/CurrencyrateService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CURRENCYRATESERVICE_WSDL_LOCATION = url;
        CURRENCYRATESERVICE_EXCEPTION = e;
    }

    public CurrencyrateService() {
        super(__getWsdlLocation(), CURRENCYRATESERVICE_QNAME);
    }

    public CurrencyrateService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CURRENCYRATESERVICE_QNAME, features);
    }

    public CurrencyrateService(URL wsdlLocation) {
        super(wsdlLocation, CURRENCYRATESERVICE_QNAME);
    }

    public CurrencyrateService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CURRENCYRATESERVICE_QNAME, features);
    }

    public CurrencyrateService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CurrencyrateService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Currencyrate
     */
    @WebEndpoint(name = "CurrencyratePort")
    public Currencyrate getCurrencyratePort() {
        return super.getPort(new QName("http://currencyrate/", "CurrencyratePort"), Currencyrate.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Currencyrate
     */
    @WebEndpoint(name = "CurrencyratePort")
    public Currencyrate getCurrencyratePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://currencyrate/", "CurrencyratePort"), Currencyrate.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CURRENCYRATESERVICE_EXCEPTION!= null) {
            throw CURRENCYRATESERVICE_EXCEPTION;
        }
        return CURRENCYRATESERVICE_WSDL_LOCATION;
    }

}
